ePS/Controllers/MyAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ePS.Controllers
{

    [Authorize]
    public class MyAccountController : Controller
    {

        const string SUB_DOMAIN_IS_DEVELOPMENT = "dev";

        [AllowAnonymous]
        public ActionResult ResetPassword(string id) {

            var passwordResetToken = (id ?? string.Empty).Trim();

            if (passwordResetToken == string.Empty) {
                return HttpNotFound();
            };

            ViewBag.PasswordResetToken = passwordResetToken;

            return View();
        }
        
        //[AllowAnonymous]    -- Commented out by Scott to fix #406  
        public ActionResult Index()
        {
            ViewBag.Title = "MyAccount | eCommerce for the Wound Care Professional | Adenitrax ";
            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());

            return View("MyAccount");
        }

        public ActionResult OrderPreferences()
        {
            ViewBag.Title = "Order Preferences | eCommerce for the professional grower | ePlantSource";
            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());
            return View();
        }
        public ActionResult PaymentOptions(string id)
        {
            const string PAGE_MODE_ALL = "all";
            const string PAGE_MODE_METHODS = "paymentmethods";
            const string PAGE_MODE_CARDS = "creditcards";
            const string PAGE_MODE_LINE = "lineofcredit";

            //clarify value of id
            id = id ?? string.Empty;
            id = id.Trim().ToLower();
            //if id != open OR shipped then id = all
            if (id != PAGE_MODE_METHODS && id != PAGE_MODE_CARDS && id != PAGE_MODE_LINE) { id = PAGE_MODE_ALL; };
            ViewBag.PageMode = id;

            ViewBag.Title = "Payment Options | eCommerce for the Wound Care Professional | Adenitrax";
            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());
            return View();
        }

        public ActionResult ManageAddresses(string id)
        {
            const string PAGE_MODE_ALL = "all";
            const string PAGE_MODE_METHODS = "paymentmethods";
            const string PAGE_MODE_CARDS = "creditcards";
            const string PAGE_MODE_LINE = "lineofcredit";

            //clarify value of id
            id = id ?? string.Empty;
            id = id.Trim().ToLower();
            //if id != open OR shipped then id = all
            if (id != PAGE_MODE_METHODS && id != PAGE_MODE_CARDS && id != PAGE_MODE_LINE) { id = PAGE_MODE_ALL; };
            ViewBag.PageMode = id;

            ViewBag.Title = "Payment Options | eCommerce for the Wound Care Professional | Adenitrax";
            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());
            return View();
        }



        public ActionResult Claims()
        {

            ViewBag.Title = "Track Claims | eCommerce for the Wound Care Professional | Adenitrax";

            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());


            return View();
        }

        public ActionResult SubmitClaim()
        {

            ViewBag.Title = "Submit Claim | eCommerce for the Wound Care Professional | Adenitraxe";

            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());


            return View();
        }

        public ActionResult TransactionSummary(string id)
        {

            ViewBag.Title = "Transactions | eCommerce for the Wound Care Professional | Adenitrax";
            const string PAGE_MODE_ALL = "all";
            const string PAGE_MODE_STATEMENT = "statement";
            const string PAGE_MODE_HISTORY = "history";
            //clarify value of id
            id = id ?? string.Empty;
            id = id.Trim().ToLower();
            if (id != PAGE_MODE_STATEMENT && id != PAGE_MODE_HISTORY) { id = PAGE_MODE_ALL; };
            ViewBag.PageMode = id;


            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());


            return View();
        }

        public ActionResult OrdersPDF()
        {

            ViewBag.Title = "Order Confirmation | eCommerce for the Wound Care Professional | Adenitraxe";



            return View();
        }
        public ActionResult Orders(string id)
        {
            ViewBag.Title = "Orders | eCommerce for the Wound Care Professional | Adenitrax";

            const string PAGE_MODE_ALL = "all";
            const string PAGE_MODE_OPEN = "open";
            const string PAGE_MODE_SHIPPED = "shipped";
            const string PAGE_MODE_CANCELLED = "cancelled";

            //clarify value of id
            id = id ?? string.Empty;
            id = id.Trim().ToLower();
            //if id != open OR shipped then id = all
            if (id != PAGE_MODE_OPEN && id != PAGE_MODE_SHIPPED && id != PAGE_MODE_CANCELLED) { id = PAGE_MODE_ALL; };
            ViewBag.PageMode = id;

            //show/hide TestInfo based on AppSetting
            ViewBag.ShowTestInfo = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());

            return View();
        }

        public ActionResult AccountSettings(string id)
        {
            ViewBag.Title = "Settings | eCommerce for the Wound Care Professional | Adenitraxe";
            const string PAGE_MODE_ALL = "all";
            const string PAGE_MODE_ACCOUNT_SETTINGS = "settings";
            const string PAGE_MODE_EMAIL_PREFERENCES = "email";

            //clarify value of id
            id = id ?? string.Empty;
            id = id.Trim().ToLower();
            //if id != open OR shipped then id = all
            if (id != PAGE_MODE_ACCOUNT_SETTINGS && id != PAGE_MODE_EMAIL_PREFERENCES) { id = PAGE_MODE_ALL; };
            ViewBag.PageMode = id;

            //show/hide TestInfo based on AppSetting
            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());

            return View();
        }


        public ActionResult Users(string id)
        {
            ViewBag.Title = "Users | eCommerce for the Wound Care Professional | Adenitrax";
            const string PAGE_MODE_ALL = "all";
            const string PAGE_MODE_ADD_USER = "add";
            const string PAGE_MODE_MANAGE_USERS = "manage";

            //clarify value of id
            id = id ?? string.Empty;
            id = id.Trim().ToLower();
            //if id != open OR shipped then id = all
            if (id != PAGE_MODE_ADD_USER && id != PAGE_MODE_MANAGE_USERS) { id = PAGE_MODE_ALL; };
            ViewBag.PageMode = id;

            //show/hide TestInfo based on AppSetting
            ViewBag.RunningInDevMode = (SUB_DOMAIN_IS_DEVELOPMENT == System.Configuration.ConfigurationManager.AppSettings["SubDomain"].ToLower());

            return View();
        }

        public ActionResult UnderConstruction(string title)
        {
            ViewBag.Title = title;
            ViewBag.Message = "This page is under construction.";

            return View();
        }

        [AllowAnonymous]
        public ActionResult TermsAndConditions(string id)
        {
            ViewBag.Title = "Terms-Conditions | eCommerce for the Wound Care Professional | Adenitrax";


            return View();
        }

    }
}

ePS/Controllers/api/AccountSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;

using System.Web.Http;
using AttributeRouting.Web.Http;
using ePS.Models;
using ePS.Models.AccountSettingsApi;

using BusinessObjectServices;

namespace ePS.Controllers.api
{
    [Authorize]
    public class AccountSettingsController : ApiControllerBase
    {

        private bool IsAccountAdministrator
        {
            //ToDo: Replace this by adding GetCurrentUserRole to ApiControllerBase once Account Admin Role is working
            get
            {
                //Determine if authenticated user has Account Admin Role

                var userGuid = GetCurrentUserGuid();
                var personService = new BusinessObjectServices.PersonService();
                var person = personService.GetPersonFromUser(userGuid);
                var role = person.UserRole;
                //ToDo: The above currently does not return a UserRole
                //either enable UserRole if that is where this information should be gotten
                //or replace above code to determine if user is Admin

                //ToDo: This his hard-coded until above code is operational
                return true;

            }
        }

        [GET("api/AccountSettings/GetUserIsAccountAdministrator", RouteName = "GetUserIsAccountAdministrator")]
        public object GetUserIsAccountAdministrator([FromUri]Guid id)
        {
            //NOTE: no models needed for this, anonamous object returned.
            //Could not get here unless authenticated
            var success = id != Guid.Empty; //must have a valid user Guid to get valid answer
            var isAuthenticated = false;
            if (success) { isAuthenticated = (GetCurrentUserGuid() != Guid.Empty); }
            var response = new
            {
                IsAuthenticated = isAuthenticated,
                Success = success,
                IsAccountAdministrator
            };
            return response;
        }


        [GET("api/AccountSettings/GetCurrentAccountSettings", RouteName = "GetCurrentAccountSettings")]
        public GetResponseModel GetCurrentAccountSettings()
        {
            //Note: This takes no parameters and returns the Account Settings based on the currently authenticated user
            var request = new GetRequestModel()
            {
                AccountGuid = GetCurrentUserGuid()
            };
            
            var response = new GetResponseModel(GetCurrentUserGuid(), request);
            var isAccountAdministrator = this.IsAccountAdministrator;
            response.AccountSettings.IsAccountAdministrator = isAccountAdministrator;
            return response;
        }
        
        [GET("api/AccountSettings/GetUserAccountSettings", RouteName = "GetUserAccountSettings")]
        public GetResponseModel GetUserAccountSettings([FromUri]GetRequestModel request)
        {
            //Note: This action takes a valid Account Guid and returns Account Settings for that Account
            //ToDo: There is a problem with this to straighten out.  The Guid coming in here is supposed to be Account Guid, not User Guid.
            //  This action uses the GetResponse as the one based on current user.  Maybe it should have one based on Account Guid, not User Guid.
            var response = new GetResponseModel(GetCurrentUserGuid(), request);
            var isAccountAdministrator = this.IsAccountAdministrator;
            response.AccountSettings.IsAccountAdministrator = isAccountAdministrator;
            
            return response;
        }




        [AcceptVerbs("POST")]
        [POST("api/AccountSettings/Update", RouteName = "PostUpdateAccountSettings")]
        public PostResponseModel PostUpdate(PostRequestModel request)
        {

            var response = new PostResponseModel(GetCurrentUserGuid(), request);
            return response;
        }


        [AcceptVerbs("PUT")]
        [PUT("api/AccountSettings/Create/", RouteName = "PutCreateAccountSettings")]
        public PutResponseModel PutCreate(PutRequestModel request)
        {
            
            
            var response = new PutResponseModel(GetCurrentUserGuid(), request);
            
            return response;
        }

        [AcceptVerbs("DELETE")]
        [DELETE("api/AccountSettings/Delete/{accountGuid}", RouteName = "DeleteAccountSettings")]
        public object Delete(Guid accountGuid)
        {
            //    //Note: This action takes a valid Account Guid and deletes Account Settings for that Account

            var success = (accountGuid != Guid.Empty);
            if (success) {
                //ToDo: Code to Delete Account Settings, returning a boolean
                success = true;  //value resulting from delete process
            }

            var response = new
            {
                Success = success,
                IsAuthenticated = true,
                this.IsAccountAdministrator,
                AccountGuid = accountGuid
            };
            return response;

        }

    }
}

ePS/Controllers/api/ClaimController.cs
using System;
using System.Web;
using System.Web.Http;
using ePS.Models.ClaimApi;
using ePS.Types;
using AttributeRouting.Web.Http;

namespace ePS.Controllers.api
{
    public class ClaimController : ApiControllerBase
    {
         [GET("api/claims")]
        public GetResponseSummaryModel GetMyClaims()
        {
            return new GetResponseSummaryModel(GetCurrentUserGuid(), new GetSummaryRequestModel() { RequestType = GetSummaryRequestModel.RequestTypeEnum.MyClaims.ToString() });
        }

        

    
        


    }
}

ePS/Controllers/api/OrderPreferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AttributeRouting.Web.Http;
using ePS.Models.GrowerApi;

namespace ePS.Controllers.api
{
    public class OrderPreferencesController : ApiControllerBase
    {

        [GET("api/OrderPreferences/AllowSubstitutions")]
        public object Get()
        {
            GetAllowSubstitutionsResponseModel oResponse = new GetAllowSubstitutionsResponseModel(GetCurrentUserGuid());
            return oResponse;
        }

        [PUT("api/OrderPreferences/{NewValue:bool}")]
        public object Put(bool newValue)
        {
            var currentValue = newValue;
            var AllowSubstitutionsRequest = new PutAllowSubstitutionsRequestModel();
           
            PutAllowSubstitutionsResponseModel  oResponse = new PutAllowSubstitutionsResponseModel(GetCurrentUserGuid(), currentValue, AllowSubstitutionsRequest);
            return oResponse;
        }

    }
}

ePS/Controllers/api/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ePS.Models;
using ePS.Models.UserApi;
using AttributeRouting.Web.Http;

namespace ePS.Controllers.api
{
    public class UserController : ApiControllerBase
    {

        [GET("api/user/growerusers")]
        public GetGrowerUserResponseModel GetGrowerUsers()
        {

            var response = new GetGrowerUserResponseModel(GetCurrentUserGuid());
            return response;
            //return new GetGrowerUserResponseModel(GetCurrentUserGuid());

        }

        [POST("/api/user/post")]
        public PostGrowerUserResponseModel Post (PostGrowerUserRequestModel request)
        {
            var response = new PostGrowerUserResponseModel(GetCurrentUserGuid(), request);
            return response;
        }

        [PUT("api/userrole/put")]
        public PutGrowerUserRoleResponseModel PutRole([FromBody]PutGrowerUserRoleRequestModel request)
        {
            return new PutGrowerUserRoleResponseModel(GetCurrentUserGuid(), request);
        }
        [PUT("api/userdelete/put")]
        public PutGrowerUserDeleteResponseModel PutRole2([FromBody]PutGrowerUserDeleteRequestModel request)
        {
            return new PutGrowerUserDeleteResponseModel(GetCurrentUserGuid(), request);
        }
        
        //public PutGrowerUserDeleteResponseModel DeleteUser([FromBody]PutGrowerUserDeleteRequestModel request)
        //{
        //    var response = new PutGrowerUserDeleteResponseModel(GetCurrentUserGuid(), request);
        //    return response;
        //}
      
        //[POST("/api/userrole/post")]
        //public PostGrowerUserRoleResponseModel PostUpdate(PutGrowerUserRoleRequestModel request)
        //{
        //    var response = new PostGrowerUserRoleResponseModel(GetCurrentUserGuid(), request);
        //    return response;
        //}

       


    }
}

ePS/Views/MyAccount/AccountSettings.cshtml
@{
    ViewBag.PageMode = ViewBag.PageMode ?? "all";
    ViewBag.Title = ViewBag.Title ?? "Account Settings";

    ViewBag.RunningInDevMode = ViewBag.RunningInDevMode ?? false;   //default to false
}


<div id="page_content">

    <h1>Account Settings</h1>

    <div id="account_settings_container" class="accordions_collapsed">
        <h2 class ="accordion_header_bars">Update Account Settings</h2>
        <div class="accordion_disabled_displays">??</div>
        <div class="accordion_displays"></div>
    </div>
        
    <div id="email_preferences_container" class="accordions_collapsed">
        <h2 class ="accordion_header_bars">Email Preferences</h2>
        <div class="accordion_disabled_displays">??</div>
        <div class="accordion_displays">
            <ul id="account_options_list">
                <li style="margin-left: 5px;">
                    <input type="checkbox" id="SubscribeToNewsLetter" checked="checked" />
                    <label for="SubscribeToNewsLetter" >
                        <span></span>
                        Yes, please send me valuable resources and updates from ePlantSource via email (you can unsubscribe at any time).
                    </label>
                <li style="margin-left: 5px;">
                    <input type="checkbox" id="SubscribeToPromotions"  checked="checked" />
                    <label for="SubscribeToPromotions">
                        <span></span>
                        Send me discounts and promotions from suppliers via email.
                    </label>
                </li>
                <li style="margin-left: 5px;">
                    <input type="checkbox" id="ClearOtherChoices" />
                    <label for="ClearOtherChoices">
                        <span></span>
                        No, I don't want to receive email communications and promotions from ePlantSource (I understand that essential emails relative to orders placed will continue.)
                    </label>
                </li>
            </ul>
        </div>
    </div>
    
    
</div>


@if(1==2){

<div id="test_area" style="display:block; height:340px; border:dotted 4px #ccc;">
    <div id="test_area_left_div">
        
        <span style="margin-top:6px;" id="test_data_show_all">Display client-side data</span><br />
        
        <span style="margin-top:6px;" id="test_api_user_is_account_administrator">IsAccountAdministrator API</span><br />
        <span style="margin-top:6px;" id="test_api_current_account_settings">Current Account Settings api</span><br />

        <span style="margin-top:6px;" id="test_api_account_settings">Specific Account Settings api</span><br />
@*        <span style="margin-top:6px;" id="test_data_account_settings">Settings Data</span><br />*@

        <span style="margin-top:6px;" id="test_api_put_account_settings">PUT Account Settings api</span><br />
        <span style="margin-top:6px;" id="test_api_post_account_settings">POST Account Settings api</span><br />
        <span style="margin-top:6px;" id="test_api_delete_account_settings">DELETE Account Settings api</span><br />



        <span style="margin-top:6px;" id="test_api_email_preferences">Email Preferences api</span><br />
        <span style="margin-top:6px;" id="test_api_put_email_preferences">PUT Email Preference api</span><br />
        <span style="margin-top:6px;" id="test_api_post_email_preferences">POST Email Preference api</span><br />
        <span style="margin-top:6px;" id="test_api_delete_email_preferences">DELETE Email Preference api</span><br />

@*        <span style="margin-top:6px;" id="test_data_email_preferences">Emails Data</span><br />*@
    </div>
    <div id="test_area_right_div">
        <div id="test_area_results_display" style="clear:both;">???</div>
    </div>
</div>

}





@section scripts {
    @*Use Bundle for PRODuction*@

@*
    @Scripts.Render("~/bundles/PageScripts/AccountSettings")  
*@


    @*Use files during Development*@    
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <script src="~/Scripts/numeral.min.js"></script>
    <script src="~/Scripts/eps_expanse.js"></script>
    <script src="~/Scripts/PageScripts/AccountSettings.js"></script>
    




    <script type="text/javascript">

        $(document).ready(function () {
            var breadCrumbs = [];
            breadCrumbs.push({ Id: "", Type: "anchor", Text: "Home", Href: "/", Title: "Home Page", State: "Active" });
            breadCrumbs.push({ Id: "", Type: "anchor", Text: "My Account", Href: "/myaccount", Title: "My Account Page", State: "Active" });
            breadCrumbs.push({ Id: "", Type: "span", Text: "Account Settings / @ViewBag.PageMode", Href: "", Title: "You are here!", State: "Active" });
            breadCrumbModel.ClearDisplay();
            breadCrumbModel.Display(breadCrumbs);

            viewModel.config.pageMode = "@ViewBag.PageMode";

            viewModel.init();

        });


    </script>
}


@section styles {
    <link href="~/Content/styles/AccountSettings.css" rel="stylesheet" />

    <style type="text/css">
        /********************** Test Area CSS ********************/

        .ui-button-text {
            font-size: 10px;
        }
        #test_area_left_div {
            float: left;
            height: 340px;
            max-height: 340px;
            width: 275px;
            font-size: 12px;
            border-right: solid 10px #f0f0f0;
        }

        #test_area_left_div p {
            margin:0;
            padding:0;
            font-size:12px;
        }

        #test_area_right_div {
            float:left;
            width:975px;
            height:340px;
            max-height:340px;
            font-size:12px;
            border: dotted 0px #008;
        }
        #test_area_results_display {
            max-height:335px;
            overflow-y:scroll;
        }
    </style>
}

ePS/Views/MyAccount/MyAccount.cshtml
@{
    ViewBag.Title = ViewBag.Title ?? "My Account";
    ViewBag.RunningInDevMode = ViewBag.RunningInDevMode ?? false;   //default to false
}

<h1>My Account</h1>
 <div id="myAccount_section">
   <h2 class="header_bars">Order and Account Activity</h2>
   <div id="myAccount_subsection">
      <h3>Order Summary</h3> 
      @Html.ActionLink("Open Orders", "Orders", "MyAccount", new {id="open"}, null)
      <br>
      @Html.ActionLink("Shipped Orders", "Orders", "MyAccount", new {id="shipped"}, null)
      <br>
      @Html.ActionLink("Cancelled Orders", "Orders", "MyAccount", new{id="cancelled"}, null)
   </div> <!--#my_Account_subsection-->
   <div id="myAccount_subsection">
      <h3>Claims</h3> 
      @Html.ActionLink("Track claims", "Claims", "MyAccount", null, null)
      <br>
      @Html.ActionLink("Submit new claim", "Claims", "MyAccount", null, null)
   </div> <!--#my_Account_subsection-->
   <div id="myAccount_subsection">
      <h3>Transaction Summary</h3>  
      @Html.ActionLink("Statement of Account", "TransactionSummary", "MyAccount", new {id="Statement" }, null)
      <br>
      @Html.ActionLink("Account Transaction History", "TransactionSummary", "MyAccount", new {id="History" }, null)
  </div> <!--#myAccount_subsection-->           
 </div> <!--#my_Account_section-->
 
 <div id="myAccount_section">
   <h2 class="header_bars">Company Preferences</h2>
   <div id="myAccount_subsection">
      <h3>Payment Options</h3> 
      @Html.ActionLink("Manage Payment Methods", "PaymentOptions", "MyAccount", new {id="paymentmethods"}, null)
      <br>
      @Html.ActionLink("Manage Credit Cards", "PaymentOptions", "MyAccount", new {id="creditcards"}, null)
      <br>
      @Html.ActionLink("Manage Line of Credit", "PaymentOptions", "MyAccount", new {id="lineofcredit"}, null)
   </div> <!--#my_Account_subsection-->
   <div id="myAccount_subsection">
      <h3>Ship To Locations</h3> 
      @Html.ActionLink("Manage Ship To Locations", "ManageAddresses", "MyAccount", new {id="manageaddresses"}, null)
   </div> <!--#my_Account_subsection-->
   <div id="myAccount_subsection">
      <h3>Order Preferences</h3>  
      @Html.ActionLink("Substitutions", "OrderPreferences", "MyAccount", new {id="substitutions"}, null)
  </div> <!--#myAccount_subsection-->           
 </div> <!--#my_Account_section-->
 
 <div id="myAccount_section">
   <h2 class="header_bars">User Preferences</h2>
   @*<div id="myAccount_subsection">
      <h3>Account Settings</h3> 
      @Html.ActionLink("Update Account Settings", "AccountSettings", "MyAccount", new {id="settings"}, null)
   </div>*@
     <!--#my_Account_subsection-->
   <div id="myAccount_subsection">
      <h3>Users</h3> 
      @Html.ActionLink("Add users", "Users", "MyAccount", new {id = "add" }, null)
	  <br>
      @Html.ActionLink("Manage users", "Users", "MyAccount", new {id = "manage" }, null)
   </div> <!--#my_Account_subsection-->       
 </div> <!--#my_Account_section-->
 

<!--scripts from original -->
@section scripts {

@*Use Bundle for PRODuction*@
    @*@Scripts.Render("~/bundles/PageScripts/MyAccount")*@ 
    
@*Use files during Development   *@ 
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <script src="~/Scripts/numeral.min.js"></script>
    <script src="~/Scripts/eps_expanse.js"></script>
    <script src="~/Scripts/pageScripts/MyAccount.js"></script>

    <script type="text/javascript">


        $(document).ready(function () {

            var breadCrumbs = [];
            breadCrumbs.push({ Id: "", Type: "anchor", Text: "Home", Href: "/", Title: "Home Page", State: "Active" });
            //breadCrumbs.push({ Id: "", Type: "anchor", Text: "My Account", Href: "/MyAccount", Title: "My Account Page", State: "Active" });
            breadCrumbs.push({ Id: "", Type: "span", Text: "MyAccount", Href: "", Title: "You are here!", State: "Active" });
            breadCrumbModel.ClearDisplay();
            breadCrumbModel.Display(breadCrumbs);

            //Init function

            viewModel.init();


        });



    </script>
}
        

@section styles {
    <link href="~/Content/styles/MyAccount.css" rel="stylesheet" />
    <link href="~/Content/styles/eps_expanse.css" rel="stylesheet" />

    <style type="text/css">

    </style>
}
  

ePS/Views/MyAccount/OrdersPDF.cshtml
@{
    ViewBag.Title = ViewBag.Title ?? "OrdersPDF";
    ViewBag.PageMode = ViewBag.PageMode ?? "";
    ViewBag.ShowTestInfo = ViewBag.ShowTestInfo ?? false;   //default to false

}



<body>


    <a href="https://epsstorage.blob.core.windows.net/invoicepdf/I-000909.pdf" download="MyFile">Download it!</a>
</body>

ePS/Views/MyAccount/TermsAndConditions.cshtml
@{
    ViewBag.Title = ViewBag.Title ?? "ePlantSource.com|Terms and Conditions";
}

@section styles {
    <style type="text/css">


        #page_content {
            height:725px;
        }
        #terms_and_conditions_container {
            margin:5px auto 0 auto;
            padding:0;
            width: 100%;
            height: 675px;
            border: 1px dashed #ccc;
        }

    </style>
}


<div id="page_content">

    <iframe id="terms_and_conditions_container" src="/images/pdfs/ePlantSource_TermsAndConditions.pdf">

    </iframe>

@*    <p>Download ePlantSource.com <a href="/images/pdfs/ePlantSource_TermsAndConditions.pdf" target="_blank">Terms and Condition</a>.</p>

     <form><input type="button" value="Download Now" onClick="window.location.href = '/images/pdfs/ePlantSource_TermsAndConditions.pdf'"></form> *@

</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            var breadCrumbs = [];
            breadCrumbs.push({ Id: "", Type: "anchor", Text: "Home", Href: "/", Title: "Home Page", State: "Active" });
            breadCrumbs.push({ Id: "", Type: "span", Text: "Terms and Conditions", Href: "", Title: "You are here!", State: "Active" });
            breadCrumbModel.ClearDisplay();
            breadCrumbModel.Display(breadCrumbs);

        });

    </script>

}

ePS/Views/MyAccount/UnderConstruction.cshtml
@*@{
    ViewBag.Title = "UnderContruction";
}*@

<h2>@ViewBag.Title</h2>
<div>@ViewBag.Message</div>
<div>Comming Soon</div>
<div></div>
<div></div>